import type { RecommendationResult, FormData } from '../types';

export type CodeType = 'training' | 'inference' | 'deployment' | 'api-client' | 'folder-structure';

export interface GeneratedCode {
  filename: string;
  content: string;
  language: string;
  description: string;
}

export const generateMLCode = (
  codeType: CodeType,
  recommendations: RecommendationResult,
  formData: FormData
): GeneratedCode[] => {
  switch (codeType) {
    case 'training':
      return generateTrainingCode(recommendations, formData);
    case 'inference':
      return generateInferenceCode(recommendations, formData);
    case 'deployment':
      return generateDeploymentCode(recommendations, formData);
    case 'api-client':
      return generateAPIClientCode(recommendations, formData);
    case 'folder-structure':
      return generateFolderStructure(recommendations, formData);
    default:
      return [];
  }
};

const generateTrainingCode = (recommendations: RecommendationResult, formData: FormData): GeneratedCode[] => {
  const isCV = formData.projectDetails.useCaseType === 'CV';
  const platform = formData.projectDetails.deploymentPlatform;
  
  if (platform === 'AWS SageMaker') {
    return generateSageMakerTrainingCode(recommendations, formData, isCV);
  }
  
  return generateGenericTrainingCode(recommendations, formData, isCV);
};

const generateSageMakerTrainingCode = (
  recommendations: RecommendationResult,
  formData: FormData,
  isCV: boolean
): GeneratedCode[] => {
  const modelName = recommendations.recommendedModel.name;
  const taskType = formData.projectDetails.taskType;

  
  const trainScript = `"""
SageMaker Training Script for ${modelName}
Task: ${taskType}
Generated by AI Model Recommendation Agent
"""

import os
import json
import argparse
import boto3
import sagemaker
from sagemaker.estimator import Estimator
${isCV ? `
import torch
import torch.nn as nn
from torchvision import models, transforms
from torch.utils.data import DataLoader, Dataset
` : `
from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments
`}

def parse_args():
    parser = argparse.ArgumentParser()
    
    # Hyperparameters
    parser.add_argument('--epochs', type=int, default=10)
    parser.add_argument('--batch-size', type=int, default=32)
    parser.add_argument('--learning-rate', type=float, default=0.001)
    
    # SageMaker specific arguments
    parser.add_argument('--model-dir', type=str, default=os.environ.get('SM_MODEL_DIR'))
    parser.add_argument('--train', type=str, default=os.environ.get('SM_CHANNEL_TRAIN'))
    parser.add_argument('--test', type=str, default=os.environ.get('SM_CHANNEL_TEST'))
    
    return parser.parse_args()

${isCV ? `
class CustomDataset(Dataset):
    def __init__(self, data_dir, transform=None):
        self.data_dir = data_dir
        self.transform = transform
        # Load your dataset here
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        # Implement data loading logic
        pass

def create_model():
    """Create and return the model"""
    model = models.${modelName.toLowerCase().includes('resnet') ? 'resnet50' : 'efficientnet_b0'}(pretrained=True)
    # Modify final layer for your task
    num_classes = ${formData.dataset?.size ? Math.min(100, Math.floor(formData.dataset.size / 100)) : 10}
    model.fc = nn.Linear(model.fc.in_features, num_classes)
    return model
` : `
def create_model(model_name="${modelName}"):
    """Create and return the model"""
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=${formData.constraints?.accuracyTarget || 2}
    )
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return model, tokenizer
`}

def train(args):
    """Main training function"""
    print(f"Training ${modelName} for ${taskType}")
    print(f"Training data location: {args.train}")
    
${isCV ? `    
    # Setup data loaders
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    train_dataset = CustomDataset(args.train, transform=transform)
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)
    
    # Create model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = create_model().to(device)
    
    # Training setup
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=args.learning_rate)
    
    # Training loop
    for epoch in range(args.epochs):
        model.train()
        running_loss = 0.0
        
        for batch_idx, (data, target) in enumerate(train_loader):
            data, target = data.to(device), target.to(device)
            
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()
            
            running_loss += loss.item()
            
            if batch_idx % 10 == 0:
                print(f'Epoch: {epoch}, Batch: {batch_idx}, Loss: {loss.item():.4f}')
        
        print(f'Epoch {epoch} completed. Average Loss: {running_loss/len(train_loader):.4f}')
    
    # Save model
    torch.save(model.state_dict(), os.path.join(args.model_dir, 'model.pth'))
` : `
    # Load and prepare data
    model, tokenizer = create_model()
    
    # Setup training arguments
    training_args = TrainingArguments(
        output_dir=args.model_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        logging_dir=f'{args.model_dir}/logs',
        logging_steps=10,
        save_strategy="epoch",
    )
    
    # Create trainer and train
    trainer = Trainer(
        model=model,
        args=training_args,
        # Add your datasets here
    )
    
    trainer.train()
    
    # Save model
    model.save_pretrained(args.model_dir)
    tokenizer.save_pretrained(args.model_dir)
`}
    
    print("Training completed successfully!")

if __name__ == '__main__':
    args = parse_args()
    train(args)
`;

  const sagemakerJobScript = `"""
SageMaker Training Job Launcher
Run this script to start a training job on AWS SageMaker
"""

import boto3
import sagemaker
from sagemaker.estimator import Estimator
from sagemaker.pytorch import PyTorch
from datetime import datetime

# Configuration
ROLE = 'arn:aws:iam::YOUR_ACCOUNT_ID:role/SageMakerExecutionRole'  # Replace with your role
BUCKET = 'your-s3-bucket'  # Replace with your S3 bucket
INSTANCE_TYPE = '${recommendations.instanceRecommendations[0]?.instanceType || 'ml.p3.2xlarge'}'
INSTANCE_COUNT = 1

def launch_training_job():
    """Launch SageMaker training job"""
    
    # Initialize SageMaker session
    sagemaker_session = sagemaker.Session()
    
    # Define training job name
    job_name = f'${modelName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-{datetime.now().strftime("%Y%m%d-%H%M%S")}'
    
    # Create estimator
    estimator = PyTorch(
        entry_point='train.py',
        role=ROLE,
        instance_type=INSTANCE_TYPE,
        instance_count=INSTANCE_COUNT,
        framework_version='2.0.0',
        py_version='py310',
        hyperparameters={
            'epochs': 10,
            'batch-size': 32,
            'learning-rate': 0.001,
        },
        output_path=f's3://{BUCKET}/output',
        base_job_name=job_name,
        ${formData.costSimulation.workloadType !== 'inference-only' ? `use_spot_instances=True,
        max_wait=7200,  # 2 hours
        max_run=3600,   # 1 hour` : ''}
    )
    
    # Start training
    print(f"Starting training job: {job_name}")
    print(f"Instance type: {INSTANCE_TYPE}")
    print(f"Estimated cost: ${recommendations.computeEstimate.monthlyCost || 'N/A'}")
    
    estimator.fit({
        'train': f's3://{BUCKET}/data/train',
        'test': f's3://{BUCKET}/data/test'
    })
    
    print(f"Training job completed!")
    print(f"Model artifacts: {estimator.model_data}")
    
    return estimator

if __name__ == '__main__':
    estimator = launch_training_job()
`;

  return [
    {
      filename: 'train.py',
      content: trainScript,
      language: 'python',
      description: 'SageMaker training script with model definition and training loop'
    },
    {
      filename: 'launch_training.py',
      content: sagemakerJobScript,
      language: 'python',
      description: 'Script to launch SageMaker training job with recommended configuration'
    }
  ];
};

const generateGenericTrainingCode = (
  _recommendations: RecommendationResult,
  _formData: FormData,
  _isCV: boolean
): GeneratedCode[] => {
  // Generic training code for non-SageMaker platforms
  return [{
    filename: 'train.py',
    content: '# Generic training script\n# Platform-specific implementation needed',
    language: 'python',
    description: 'Generic training script template'
  }];
};


const generateInferenceCode = (recommendations: RecommendationResult, formData: FormData): GeneratedCode[] => {
  const isCV = formData.projectDetails.useCaseType === 'CV';
  const modelName = recommendations.recommendedModel.name;
  
  const inferenceScript = `"""
SageMaker Inference Script
Handles model loading and prediction requests
"""

import json
import os
${isCV ? `
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import io
import base64
` : `
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
`}

# Model loading
model = None
${!isCV ? 'tokenizer = None' : ''}

def model_fn(model_dir):
    """
    Load the model for inference
    Called once when the endpoint is created
    """
    global model${!isCV ? ', tokenizer' : ''}
    
    print(f"Loading model from {model_dir}")
    
${isCV ? `    
    # Load PyTorch model
    model = models.${modelName.toLowerCase().includes('resnet') ? 'resnet50' : 'efficientnet_b0'}()
    model.load_state_dict(torch.load(os.path.join(model_dir, 'model.pth')))
    model.eval()
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)
` : `
    # Load transformer model
    model = AutoModelForSequenceClassification.from_pretrained(model_dir)
    tokenizer = AutoTokenizer.from_pretrained(model_dir)
    model.eval()
`}
    
    print("Model loaded successfully")
    return model

def input_fn(request_body, content_type='application/json'):
    """
    Deserialize and prepare the prediction input
    """
    
    if content_type == 'application/json':
        input_data = json.loads(request_body)
${isCV ? `        
        # Decode base64 image
        image_data = base64.b64decode(input_data['image'])
        image = Image.open(io.BytesIO(image_data))
        
        # Preprocess image
        transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])
        
        return transform(image).unsqueeze(0)
` : `
        # Get text input
        text = input_data.get('text', '')
        return text
`}
    else:
        raise ValueError(f"Unsupported content type: {content_type}")

def predict_fn(input_data, model):
    """
    Apply model to the incoming request
    """
    
${isCV ? `    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    input_data = input_data.to(device)
    
    with torch.no_grad():
        output = model(input_data)
        probabilities = torch.nn.functional.softmax(output, dim=1)
        predicted_class = torch.argmax(probabilities, dim=1).item()
        confidence = probabilities[0][predicted_class].item()
    
    return {
        'predicted_class': predicted_class,
        'confidence': float(confidence),
        'probabilities': probabilities[0].tolist()
    }
` : `
    global tokenizer
    
    # Tokenize input
    inputs = tokenizer(input_data, return_tensors="pt", padding=True, truncation=True)
    
    # Get prediction
    with torch.no_grad():
        outputs = model(**inputs)
        predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
        predicted_class = torch.argmax(predictions, dim=-1).item()
        confidence = predictions[0][predicted_class].item()
    
    return {
        'predicted_class': predicted_class,
        'confidence': float(confidence),
        'probabilities': predictions[0].tolist()
    }
`}

def output_fn(prediction, accept='application/json'):
    """
    Serialize the prediction result
    """
    
    if accept == 'application/json':
        return json.dumps(prediction), accept
    
    raise ValueError(f"Unsupported accept type: {accept}")
`;

  return [{
    filename: 'inference.py',
    content: inferenceScript,
    language: 'python',
    description: 'SageMaker inference script for model serving'
  }];
};

const generateDeploymentCode = (recommendations: RecommendationResult, formData: FormData): GeneratedCode[] => {
  const deploymentScript = `"""
SageMaker Model Deployment Script
Deploy trained model to a real-time endpoint
"""

import boto3
import sagemaker
from sagemaker.pytorch import PyTorchModel
from datetime import datetime

# Configuration
ROLE = 'arn:aws:iam::YOUR_ACCOUNT_ID:role/SageMakerExecutionRole'
MODEL_DATA = 's3://your-bucket/output/model.tar.gz'  # Path to your trained model
INSTANCE_TYPE = '${recommendations.instanceRecommendations[0]?.instanceType || 'ml.m5.xlarge'}'
INSTANCE_COUNT = ${formData.costSimulation.environments || 1}

def deploy_model():
    """Deploy model to SageMaker endpoint"""
    
    # Initialize SageMaker session
    sagemaker_session = sagemaker.Session()
    
    # Create endpoint name
    endpoint_name = f'${recommendations.recommendedModel.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-endpoint-{datetime.now().strftime("%Y%m%d-%H%M%S")}'
    
    print(f"Deploying model to endpoint: {endpoint_name}")
    print(f"Instance type: {INSTANCE_TYPE}")
    print(f"Instance count: {INSTANCE_COUNT}")
    print(f"Estimated monthly cost: ${recommendations.computeEstimate.monthlyCost || 'N/A'}")
    
    # Create PyTorch model
    pytorch_model = PyTorchModel(
        model_data=MODEL_DATA,
        role=ROLE,
        entry_point='inference.py',
        framework_version='2.0.0',
        py_version='py310',
        sagemaker_session=sagemaker_session
    )
    
    # Deploy model
    predictor = pytorch_model.deploy(
        instance_type=INSTANCE_TYPE,
        initial_instance_count=INSTANCE_COUNT,
        endpoint_name=endpoint_name,
        wait=True
    )
    
    print(f"✅ Model deployed successfully!")
    print(f"Endpoint name: {endpoint_name}")
    print(f"Endpoint ARN: {predictor.endpoint}")
    
    # Test the endpoint
    test_prediction(predictor)
    
    return predictor

def test_prediction(predictor):
    """Test the deployed endpoint"""
    
    print("\\nTesting endpoint...")
    
    # Sample test data
    test_data = {
        ${formData.projectDetails.useCaseType === 'CV' 
          ? '"image": "base64_encoded_image_here"' 
          : '"text": "Sample text for testing"'}
    }
    
    try:
        response = predictor.predict(test_data)
        print(f"Test prediction successful!")
        print(f"Response: {response}")
    except Exception as e:
        print(f"Test prediction failed: {str(e)}")

def delete_endpoint(endpoint_name):
    """Delete the endpoint when no longer needed"""
    
    sagemaker_client = boto3.client('sagemaker')
    
    print(f"Deleting endpoint: {endpoint_name}")
    sagemaker_client.delete_endpoint(EndpointName=endpoint_name)
    print("Endpoint deleted successfully")

if __name__ == '__main__':
    predictor = deploy_model()
    
    # Uncomment to delete endpoint after testing
    # delete_endpoint(predictor.endpoint_name)
`;

  const requirementsFile = `# Python dependencies for ${recommendations.recommendedModel.name}
# Generated by AI Model Recommendation Agent

sagemaker>=2.150.0
boto3>=1.26.0
${formData.projectDetails.useCaseType === 'CV' ? `torch>=2.0.0
torchvision>=0.15.0
Pillow>=9.0.0` : `transformers>=4.30.0
torch>=2.0.0`}
numpy>=1.24.0
pandas>=2.0.0
scikit-learn>=1.3.0
`;

  return [
    {
      filename: 'deploy.py',
      content: deploymentScript,
      language: 'python',
      description: 'Script to deploy model to SageMaker endpoint'
    },
    {
      filename: 'requirements.txt',
      content: requirementsFile,
      language: 'text',
      description: 'Python dependencies for the project'
    }
  ];
};


const generateAPIClientCode = (_recommendations: RecommendationResult, formData: FormData): GeneratedCode[] => {
  const clientScript = `"""
API Client for SageMaker Endpoint
Use this to make predictions from your application
"""

import boto3
import json
${formData.projectDetails.useCaseType === 'CV' ? `import base64
from PIL import Image
import io` : ''}

class ModelClient:
    def __init__(self, endpoint_name):
        """
        Initialize the client
        
        Args:
            endpoint_name: Name of the SageMaker endpoint
        """
        self.endpoint_name = endpoint_name
        self.runtime = boto3.client('sagemaker-runtime')
    
    def predict(self, ${formData.projectDetails.useCaseType === 'CV' ? 'image_path' : 'text'}):
        """
        Make a prediction
        
        Args:
            ${formData.projectDetails.useCaseType === 'CV' ? 'image_path: Path to image file' : 'text: Input text string'}
        
        Returns:
            dict: Prediction results
        """
        
${formData.projectDetails.useCaseType === 'CV' ? `        # Load and encode image
        with open(image_path, 'rb') as f:
            image_bytes = f.read()
        
        image_base64 = base64.b64encode(image_bytes).decode('utf-8')
        
        payload = {
            'image': image_base64
        }` : `        payload = {
            'text': text
        }`}
        
        # Invoke endpoint
        response = self.runtime.invoke_endpoint(
            EndpointName=self.endpoint_name,
            ContentType='application/json',
            Body=json.dumps(payload)
        )
        
        # Parse response
        result = json.loads(response['Body'].read().decode())
        return result
    
    def batch_predict(self, ${formData.projectDetails.useCaseType === 'CV' ? 'image_paths' : 'texts'}):
        """
        Make predictions for multiple inputs
        
        Args:
            ${formData.projectDetails.useCaseType === 'CV' ? 'image_paths: List of image file paths' : 'texts: List of text strings'}
        
        Returns:
            list: List of prediction results
        """
        
        results = []
        for ${formData.projectDetails.useCaseType === 'CV' ? 'image_path' : 'text'} in ${formData.projectDetails.useCaseType === 'CV' ? 'image_paths' : 'texts'}:
            result = self.predict(${formData.projectDetails.useCaseType === 'CV' ? 'image_path' : 'text'})
            results.append(result)
        
        return results

# Example usage
if __name__ == '__main__':
    # Initialize client
    client = ModelClient(endpoint_name='your-endpoint-name')
    
    # Make prediction
    ${formData.projectDetails.useCaseType === 'CV' 
      ? "result = client.predict('path/to/image.jpg')" 
      : "result = client.predict('Your input text here')"}
    
    print(f"Prediction: {result}")
    print(f"Predicted class: {result['predicted_class']}")
    print(f"Confidence: {result['confidence']:.2%}")
`;

  return [{
    filename: 'client.py',
    content: clientScript,
    language: 'python',
    description: 'Python client to interact with deployed model endpoint'
  }];
};

const generateFolderStructure = (recommendations: RecommendationResult, formData: FormData): GeneratedCode[] => {
  const structure = `# Recommended Project Structure for ${recommendations.recommendedModel.name}

\`\`\`
${recommendations.recommendedModel.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-project/
│
├── data/                          # Data directory
│   ├── raw/                       # Raw data
│   ├── processed/                 # Processed data
│   └── README.md                  # Data documentation
│
├── notebooks/                     # Jupyter notebooks for exploration
│   ├── 01_data_exploration.ipynb
│   ├── 02_model_training.ipynb
│   └── 03_evaluation.ipynb
│
├── src/                           # Source code
│   ├── __init__.py
│   ├── train.py                   # Training script (generated)
│   ├── inference.py               # Inference script (generated)
│   ├── preprocessing.py           # Data preprocessing
│   └── utils.py                   # Utility functions
│
├── scripts/                       # Deployment and automation scripts
│   ├── launch_training.py         # Launch SageMaker training (generated)
│   ├── deploy.py                  # Deploy to endpoint (generated)
│   └── client.py                  # API client (generated)
│
├── tests/                         # Unit tests
│   ├── __init__.py
│   ├── test_preprocessing.py
│   └── test_inference.py
│
├── configs/                       # Configuration files
│   ├── training_config.yaml       # Training hyperparameters
│   └── deployment_config.yaml     # Deployment settings
│
├── models/                        # Saved models (local)
│   └── .gitkeep
│
├── logs/                          # Training logs
│   └── .gitkeep
│
├── requirements.txt               # Python dependencies (generated)
├── README.md                      # Project documentation
├── .gitignore                     # Git ignore file
└── setup.py                       # Package setup file
\`\`\`

## Setup Instructions

### 1. Create Project Structure
\`\`\`bash
mkdir -p data/{raw,processed} notebooks src scripts tests configs models logs
touch src/__init__.py tests/__init__.py
\`\`\`

### 2. Install Dependencies
\`\`\`bash
pip install -r requirements.txt
\`\`\`

### 3. Configure AWS Credentials
\`\`\`bash
aws configure
# Enter your AWS Access Key ID, Secret Access Key, and region
\`\`\`

### 4. Set Up S3 Bucket
\`\`\`bash
aws s3 mb s3://your-ml-project-bucket
aws s3 cp data/processed/ s3://your-ml-project-bucket/data/ --recursive
\`\`\`

### 5. Update Configuration
Edit the following files with your specific values:
- \`scripts/launch_training.py\`: Update ROLE and BUCKET
- \`scripts/deploy.py\`: Update ROLE and MODEL_DATA
- \`configs/training_config.yaml\`: Adjust hyperparameters

## Workflow

### Training
\`\`\`bash
# Local training (for testing)
python src/train.py --epochs 10 --batch-size 32

# SageMaker training
python scripts/launch_training.py
\`\`\`

### Deployment
\`\`\`bash
python scripts/deploy.py
\`\`\`

### Inference
\`\`\`bash
python scripts/client.py
\`\`\`

## Cost Optimization Tips

1. **Use Spot Instances**: Enabled in launch_training.py (saves ~70%)
2. **Right-size Instances**: Current recommendation: ${recommendations.instanceRecommendations[0]?.instanceType || 'ml.p3.2xlarge'}
3. **Auto-scaling**: Configure based on traffic patterns
4. **Monitoring**: Set up CloudWatch alarms for cost tracking

## Estimated Costs

- Training: ${recommendations.computeEstimate.monthlyCost || 'N/A'}
- Inference: ${recommendations.computeEstimate.monthlyCost || 'N/A'}
- Monthly Total: ${recommendations.computeEstimate.monthlyCost || 'N/A'}

## Next Steps

1. ✅ Generate all code files using the Code Generator
2. ✅ Set up project structure
3. ✅ Configure AWS credentials and S3
4. ⬜ Prepare and upload training data
5. ⬜ Run training job
6. ⬜ Deploy model to endpoint
7. ⬜ Test predictions
8. ⬜ Set up monitoring and alerts

## Support

For issues or questions:
- AWS SageMaker Documentation: https://docs.aws.amazon.com/sagemaker/
- Model: ${recommendations.recommendedModel.name}
- Task: ${formData.projectDetails.taskType}
`;

  return [{
    filename: 'PROJECT_STRUCTURE.md',
    content: structure,
    language: 'markdown',
    description: 'Complete project structure and setup guide'
  }];
};
